"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'honda'? I predict False.");
console.log(car == 'honda');
console.log("Is car != 'toyota'? I predict True.");
console.log(car != 'toyota');
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'Subaru'? I predict False.");
console.log(car == 'Subaru');
console.log("Is car != 'Subaru'? I predict True.");
console.log(car == 'Subaru');
console.log("Is car == 'corola'? I predict False.");
console.log(car == 'corola');
console.log("Is car.length> 5? I predict False.");
console.log(car.length > 5);
console.log("Is car.length<= 6? I predict True.");
console.log(car.length <= 6);
console.log("Is car.includes(`c`)? I predict False.");
console.log(car.includes(`c`));
